### ISSUE TITLE
Don't unpack whole file on access

### ISSUE THREAD

**Issue by JuniorJPDJ** [cybernoid/archivemount#15]
I've little problem.
I'm mounting loads of remote zips, big part of them have NO COMPRESSION.
archivemount still first loads whole file on open, then provides amount of data `read()` asked for.
That's big problem, software I'm using tries to open all files inside mounted zips and load just a bunch of kBs from N-MB files.
What if archivemount could decompress just as much data as `read()` ask for, only unpack whole on `seek()` or even don't unpack whole if possible (eg. if no compression is applied in archive - like tar or zip stored file)?

**Comment by cybernoid** [comment]
Hi,
archivemount is in passive maintenance mode. If you find a way to fix that problem send patches, I'll happily integrate them.
 
I fear reading the whole zip file and building up the tree in memory is the central concept around which a archivemount is built, so changing this would require a major rewrite.

**Comment by JuniorJPDJ** [comment]
I mean reading whole meta inside zip is ok for me, I'm talking about data inside.

**Comment by cybernoid** [comment]
Archivemount does not process the zip file itselves, the whole work is done by libarchive.
