### ISSUE TITLE
Extremely slow file access in zip files

### ISSUE THREAD

**Issue by probonopd** [cybernoid/archivemount#24]
A ~100 MB file can be unzipped in just a few seconds, but copying the same file out of a mounted zip archive using archivemount on FreeBSD takes ~10 minutes during which the `archivemount` process takes ~80% CPU.

Is this just how it is, or is this a grave bug?

**Comment by mxmlnkn** [comment]
@probonopd This is probably a duplicate of #21. Please give https://github.com/google/fuse-archive or https://github.com/mxmlnkn/ratarmount a try. Both should fix that particular issue. As to the current development stauts of archivemount, please check out the answers in #14.

**Comment by probonopd** [comment]
Thanks for the pointers @mjfwalsh.
