### ISSUE TITLE
Archivemount change some archive type to tar

### ISSUE THREAD

**Issue by og900aero** [cybernoid/archivemount#30]
I try archivemount, but I noticed that it changes the type of a couple of compressors. For example, if I mount a zip or tar.zst, then make changes in it and detach it with fusermount -u , the modified file will be changed to tar:

```
─ ✔  shyciii@debian  /home/Data  took 4.934s  
╰─$ file -Lb --mime-type scrip.tar.zst
application/x-tar

╭─ ✔  shyciii@debian  /home/Data  took 10.843s  
╰─$ file -Lb --mime-type scrip.tar.zst.orig 
application/zstd
```

**Comment by nabijaczleweli** [comment]
This was fixed in archivemount-ng, cf. #29.

**Comment by og900aero** [comment]
> This was fixed in archivemount-ng, cf. #29.

And how can I install on Debian 12?

**Comment by nabijaczleweli** [comment]
It'll be the default `archivemount` in trixie, but for bookworm:
```sh
dget -ux http://deb.debian.org/debian/pool/main/a/archivemount/archivemount_1-1.dsc
cd archivemount-1/
sudo apt build-dep .
debuild -us -uc
sudo apt install ../archivemount_1-1_amd64.deb
```

**Comment by og900aero** [comment]
> It'll be the default `archivemount` in trixie, but for bookworm:
> 
> ```shell
> dget -ux http://deb.debian.org/debian/pool/main/a/archivemount/archivemount_1-1.dsc
> cd archivemount-1/
> sudo apt build-dep .
> debuild -us -uc
> sudo apt install ../archivemount_1-1_amd64.deb
> ```

Thank u!
