### ISSUE TITLE
Support Linux PATH_MAX of 4096

### ISSUE THREAD

**Issue by ziggy90127** [cybernoid/archivemount#32]
```
$ uname -a
Linux debian12 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux
$ getconf -a | grep PATH_MAX
PATH_MAX                           4096
_POSIX_PATH_MAX                    4096
$
$ tar xf this_is_a_50_char_path.tar.gz 
$ tar xf this_is_a_1100_char_path.tar.gz 
$ du -sh this_is_a_50_char_path
4.0K	this_is_a_50_char_path
$ du -sh this_is_a_1100_char_path
172K	this_is_a_1100_char_path
$
$ mkdir -p ~/mnt/50
$ mkdir -p ~/mnt/1100
$ archivemount this_is_a_50_char_path.tar.gz ~/mnt/50
$ archivemount this_is_a_1100_char_path.tar.gz ~/mnt/1100
$ du -sh ~/mnt/50
512	/home/user/mnt/50
$ du -sh ~/mnt/1100
du: cannot access '/home/user/mnt/1100/this_is_a_1100_char_path/this_is_a_1100_char_.txt': No such file or directory
2.0K	/home/user/mnt/1100
$ 

```

[this_is_a_50_char_path.tar.gz](https://github.com/user-attachments/files/16741167/this_is_a_50_char_path.tar.gz)
[this_is_a_1100_char_path.tar.gz](https://github.com/user-attachments/files/16741168/this_is_a_1100_char_path.tar.gz)

**Comment by nabijaczleweli** [comment]
This is fixed in archivemount-ng (cf. #29),

```shell-session
$ mkdir 50 1100
$ archivemount this_is_a_50_char_path.tar.gz 50
$ du -sh 50
1k      50
$ archivemount this_is_a_1100_char_path.tar.gz 1100
$ du -sh 1100/
22k     1100/
```

**Comment by ziggy90127** [comment]
Thank you.

**Comment by ziggy90127** [comment]
To compile archive-ng on mac, I had to do:
```
< 	archive_entry_set_mtime(root->entry, st.st_mtim.tv_sec, st.st_mtim.tv_nsec);
---
> //	archive_entry_set_mtime(root->entry, st.st_mtim.tv_sec, st.st_mtim.tv_nsec);
> 	archive_entry_set_mtime(root->entry, st.st_mtime, 0);
```
Notes:
- I don't know if my change is the right thing to do.
- The original archivemount on mac handles the mac's max path of 1024, so archivemount-ng is not needed, unless there's bug fixes I'm not aware of.

**Comment by nabijaczleweli** [comment]
It isn't I think. At least not in the general case. What type/version of system is your "mac"? Does it need some special macro to get standard `struct stat` fields?

There's like so many, it's a miracle you didn't encounter like 4 on your way to test this (see the bugs sexion in the [README](https://sr.ht/~nabijaczleweli/archivemount-ng/)).

**Comment by ziggy90127** [comment]
macOS Sonoma 14.6.1
```
% uname -a
Darwin 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64 x86_64
% port list archivemount
archivemount                   @0.9.1          fuse/archivemount
```
https://opensource.apple.com/source/xnu/xnu-7195.81.3/bsd/sys/stat.h.auto.html has these macros:  
```
#if !defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)
#define st_atime st_atimespec.tv_sec
#define st_mtime st_mtimespec.tv_sec
#define st_ctime st_ctimespec.tv_sec
#define st_birthtime st_birthtimespec.tv_sec
#endif /* (!_POSIX_C_SOURCE || _DARWIN_C_SOURCE) */
```
I've only used archivemount-ng briefly under Debian 12 to peek inside an archive to see if it is correct.  I've only got 1 filename that exceeds the 1024 limit, and it's probably due to a bug.  I probably won't use it on Mac, but if archviemount-ng makes it to mainstream, I guess a one line fix will be needed.

**Comment by nabijaczleweli** [comment]
I can repro this as well on a live system (sorry for the screenshot, the only macintosh i have access to is a VM):
![](https://github.com/user-attachments/assets/1407837e-ec2b-455e-be6e-f5546cae040a)

The macro names are CRAZY in this. POSIX very clearly specifies `struct timespect st_mtim;` and *only* that. And it's not like it'd be that hard to turn whatever they have rn into the standard version compatibly, either. Apple make a functional system 2024 challenge (degree of difficulty: impossible).

If you drop your current patch and instead, after the includes (around like line 60), prepend
```c
#if __APPLE__
#define st_mtim st_mtimespec
#endif
```
does the build work?

If that's not sufficient, does it work if you also prepend `#define _DARWIN_C_SOURCE 1` before the includes (line 18)?

**Comment by ziggy90127** [comment]
It works, thanks!

```
58a59,61
> #if __APPLE__
> #define st_mtim st_mtimespec
> #endif
```

**Comment by nabijaczleweli** [comment]
Applied in https://git.sr.ht/~nabijaczleweli/archivemount-ng/commit/53dd70f05fdb6ababe7c1ca70f0f62bcf4930b5a

**Comment by ryandesign** [comment]
> The macro names are CRAZY in this. POSIX very clearly specifies `struct timespect st_mtim;` and _only_ that. And it's not like it'd be that hard to turn whatever they have rn into the standard version compatibly, either. Apple make a functional system 2024 challenge (degree of difficulty: impossible).

Let's not throw a fit about boats that sailed long ago. Mac OS X became a [POSIX-compliant certified UNIX operating](https://en.wikipedia.org/wiki/POSIX#POSIX-certified) at version 10.5 released in 2007. It conforms to the SUSv3 and POSIX 1003.1 specifications, so whatever macOS is doing must be permitted by POSIX or it would not have been certified. Most editions of Linux, as it happens, are not certified POSIX-compliant OSes.

**Comment by nabijaczleweli** [comment]
You are, of course, wrong and very annoying about it (average Apple enthusiast):

Quoth POSIX.1-2024 (Issue 8):
```
14471  struct timespec st_atim Last data access timestamp.
14472  struct timespec st_mtim Last data modification timestamp.
14473  struct timespec st_ctim Last file status change timestamp.
```
```
14498  For compatibility with earlier versions of this standard, the st_atime macro shall be defined with
14499  the value st_atim.tv_sec. Similarly, st_ctime and st_mtime shall be defined as macros with the
14500  values st_ctim.tv_sec and st_mtim.tv_sec, respectively.
```
and
```
14628 CHANGE HISTORY
14652 Issue 7
14660 Changes are made related to support for finegrained timestamps and the UTIME_NOW and
14661 UTIME_OMIT symbolic constants are added.
```

POSIX Issue 7 was published in 2008, so the macintosh (a multi-billion-dollar product) is only 2 standards and 16 years behind.

But sure, it was certified UNIX03 20 years ago so you can send e-mail about whom to drone strike (that was a joke but '03 was just in time for Iraq! so it's probably literally true). This makes it universally infallible in the eyes of the yank.
